# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8975437a9a67930a6ffbbdfa30365f03"
application_url = "https://gps-licensing-endorsement-names.trycloudflare.com"
embedded = true
name = "abc"
handle = "abc-318"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gps-licensing-endorsement-names.trycloudflare.com/auth/callback",
  "https://gps-licensing-endorsement-names.trycloudflare.com/auth/shopify/callback",
  "https://gps-licensing-endorsement-names.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
